# Pakai komputer mini yang sudah ada Node.js versi 18-nya
FROM node:18-alpine

# Kita kerja di folder /app di dalam komputer mini ini
WORKDIR /app

# Perintah yang otomatis dijalankan pas komputer mini ini nyala
CMD npm install && npm run dev
